/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    includeBuild("build-logic")
    plugins {
        kotlin("jvm") version "2.3.0"
    }
}

rootProject.name = "xide"
include(":xide-search-plugin")
include(":xide-ui")
include(":xide-rust-file-plugin")
include(":xide-settings-plugin")
include(":xide-logs-plugin")
include(":xide-core")
include(":xide-standard-plugins")
include(":xide-rc-plugin")
include(":xide-app")
include(":xide-terminal-plugin")
include(":xide-folder-tree-plugin")
include(":xide-scene-editor-plugin")

project(":xide-search-plugin").projectDir = file("xide-standard-plugins/xide-search-plugin")
project(":xide-rust-file-plugin").projectDir = file("xide-standard-plugins/xide-rust-file-plugin")
project(":xide-settings-plugin").projectDir = file("xide-standard-plugins/xide-settings-plugin")
project(":xide-logs-plugin").projectDir = file("xide-standard-plugins/xide-logs-plugin")
project(":xide-rc-plugin").projectDir = file("xide-standard-plugins/xide-rc-plugin")
project(":xide-terminal-plugin").projectDir = file("xide-standard-plugins/xide-terminal-plugin")
project(":xide-folder-tree-plugin").projectDir = file("xide-standard-plugins/xide-folder-tree-plugin")
project(":xide-scene-editor-plugin").projectDir = file("xide-standard-plugins/xide-scene-editor-plugin")
