/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.jogamp.jogl.jogl.all)
    api(libs.org.jogamp.gluegen.gluegen.rt)
    api(project(":xide-core"))
    api(project(":xide-ui"))
    runtimeOnly(libs.org.jogamp.gluegen.gluegen.rt)
    runtimeOnly(libs.org.jogamp.jogl.jogl.all)
}

description = "Xide Scene Editor Plugin"
