import org.jetbrains.kotlin.gradle.dsl.JvmTarget

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    kotlin("jvm")
}

dependencies {
    api(libs.org.jogamp.jogl.jogl.all)
    api(libs.org.jogamp.gluegen.gluegen.rt)
    api(project(":xide-core"))
    api(project(":xide-ui"))
    runtimeOnly(libs.org.jogamp.gluegen.gluegen.rt)
    runtimeOnly(libs.org.jogamp.jogl.jogl.all)
    implementation(kotlin("stdlib"))
}

kotlin {
    jvmToolchain(25)
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_25)
    }
}

description = "Xide Scene Editor Plugin"
