/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    id("scala")
}

dependencies {
    api(project(":xide-core"))
    api(project(":xide-ui"))

    implementation(libs.org.scala.lang.scala3.library)
}

description = "Xide Folder Tree Plugin"
