import java.nio.file.Files
import java.nio.file.StandardCopyOption
import java.net.URI
import java.io.File
import org.gradle.api.file.RelativePath
import org.gradle.jvm.tasks.Jar

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    application
}

val pluginProjects = listOf(
    ":xide-folder-tree-plugin",
    ":xide-terminal-plugin",
    ":xide-settings-plugin",
    ":xide-rust-file-plugin",
    ":xide-logs-plugin",
    ":xide-scene-editor-plugin",
    ":xide-rc-plugin",
    ":xide-search-plugin"
)

dependencies {
    api(project(":xide-core"))
    api(project(":xide-ui"))
    pluginProjects.forEach { runtimeOnly(project(it)) }
    testImplementation(libs.junit.junit)
}

description = "xide-app"

application {
    mainClass.set("org.xast.xide.app.Main")
}

val distRoot = rootProject.layout.projectDirectory.dir("dist")
val appDistDir = distRoot.dir("app")
val libDistDir = distRoot.dir("lib")
val pluginsDistDir = distRoot.dir("plugins")
val jdkLinuxDistDir = distRoot.dir("tools/jdk/linux")
val jdkWindowsDistDir = distRoot.dir("tools/jdk/windows")
val generatedLauncherSh = layout.buildDirectory.file("generated/dist/xide.sh")
val generatedLauncherBat = layout.buildDirectory.file("generated/dist/xide.bat")
val temurinJdkVersion = 25
val temurinDownloadsDir = layout.buildDirectory.dir("downloads/temurin")

fun downloadToFile(url: String, target: File) {
    target.parentFile.mkdirs()
    URI(url).toURL().openStream().use { input ->
        Files.copy(input, target.toPath(), StandardCopyOption.REPLACE_EXISTING)
    }
}

fun extractTarGzStripRoot(archive: File, destination: File) {
    destination.mkdirs()
    copy {
        from(tarTree(resources.gzip(archive))) {
            eachFile {
                val stripped = relativePath.segments.drop(1)
                if (stripped.isEmpty()) {
                    exclude()
                } else {
                    relativePath = RelativePath(true, *stripped.toTypedArray())
                }
            }
            includeEmptyDirs = false
        }
        into(destination)
    }
}

fun extractZipStripRoot(archive: File, destination: File) {
    destination.mkdirs()
    copy {
        from(zipTree(archive)) {
            eachFile {
                val stripped = relativePath.segments.drop(1)
                if (stripped.isEmpty()) {
                    exclude()
                } else {
                    relativePath = RelativePath(true, *stripped.toTypedArray())
                }
            }
            includeEmptyDirs = false
        }
        into(destination)
    }
}

val prepareBundledTemurinJdks by tasks.registering {
    description = "Downloads and extracts Temurin JDKs for dist/tools/jdk"
    group = "distribution"
    notCompatibleWithConfigurationCache("Uses dynamic file operations and archive extraction during packaging")

    outputs.dirs(jdkLinuxDistDir, jdkWindowsDistDir)

    doLast {
        val downloadsDir = temurinDownloadsDir.get().asFile
        val linuxArchive = File(downloadsDir, "temurin-${temurinJdkVersion}-linux-x64.tar.gz")
        val windowsArchive = File(downloadsDir, "temurin-${temurinJdkVersion}-windows-x64.zip")

        val linuxDir = jdkLinuxDistDir.asFile
        val windowsDir = jdkWindowsDistDir.asFile

        val linuxJava = File(linuxDir, "bin/java")
        val windowsJava = File(windowsDir, "bin/java.exe")

        if (!linuxJava.exists()) {
            val linuxUrl = "https://api.adoptium.net/v3/binary/latest/${temurinJdkVersion}/ga/linux/x64/jdk/hotspot/normal/eclipse?project=jdk"
            logger.lifecycle("Downloading Temurin JDK ${temurinJdkVersion} for linux/x64")
            downloadToFile(linuxUrl, linuxArchive)
            delete(linuxDir)
            extractTarGzStripRoot(linuxArchive, linuxDir)
            linuxJava.setExecutable(true)
        }

        if (!windowsJava.exists()) {
            val windowsUrl = "https://api.adoptium.net/v3/binary/latest/${temurinJdkVersion}/ga/windows/x64/jdk/hotspot/normal/eclipse?project=jdk"
            logger.lifecycle("Downloading Temurin JDK ${temurinJdkVersion} for windows/x64")
            downloadToFile(windowsUrl, windowsArchive)
            delete(windowsDir)
            extractZipStripRoot(windowsArchive, windowsDir)
        }
    }
}

val writeDistLauncher by tasks.registering {
    val launcherSh = generatedLauncherSh
    val launcherBat = generatedLauncherBat
    notCompatibleWithConfigurationCache("Generates launcher scripts during task execution")

    outputs.files(launcherSh, launcherBat)

    doLast {
        val launcherShFile = launcherSh.get().asFile
        val launcherShPath = launcherShFile.toPath()
        Files.createDirectories(launcherShPath.parent)
        Files.writeString(
            launcherShPath,
            """
            |#!/usr/bin/env bash
            |DIR="${'$'}(cd "${'$'}(dirname "${'$'}0")" && pwd)"
            |CLASSPATH="${'$'}DIR/app/xide.jar:${'$'}DIR/lib/*:${'$'}DIR/plugins/*"
            |JAVA_EXE="${'$'}DIR/tools/jdk/linux/bin/java"
            |if [ ! -x "${'$'}JAVA_EXE" ]; then
            |  echo "Missing bundled JDK at ${'$'}JAVA_EXE. Run './gradlew :xide-app:syncDistLayout' to download Temurin ${temurinJdkVersion}" >&2
            |  exit 1
            |fi
            |exec "${'$'}JAVA_EXE" -Dsun.java2d.opengl=true --enable-native-access=ALL-UNNAMED -Xms128m -Xmx1024m -cp "${'$'}CLASSPATH" org.xast.xide.app.Main "${'$'}@"
            """.trimMargin() + "\n"
        )
        launcherShFile.setExecutable(true)

        val launcherBatPath = launcherBat.get().asFile.toPath()
        Files.writeString(
            launcherBatPath,
            """
            |@echo off
            |setlocal
            |set "DIR=%~dp0"
            |set "CLASSPATH=%DIR%app\xide.jar;%DIR%lib\*;%DIR%plugins\*"
            |set "JAVA_EXE=%DIR%tools\jdk\windows\bin\java.exe"
            |if not exist "%JAVA_EXE%" (
            |  echo Missing bundled JDK at "%JAVA_EXE%". Run ".\gradlew :xide-app:syncDistLayout" to download Temurin ${temurinJdkVersion}
            |  exit /b 1
            |)
            |"%JAVA_EXE%" -Dsun.java2d.opengl=true --enable-native-access=ALL-UNNAMED -Xms128m -Xmx1024m -cp "%CLASSPATH%" org.xast.xide.app.Main %*
            |endlocal
            """.trimMargin().replace("\n", "\r\n") + "\r\n"
        )
    }
}

writeDistLauncher {
    mustRunAfter(cleanDistRuntime)
}

val cleanDistRuntime by tasks.registering(Delete::class) {
    delete(appDistDir, libDistDir, pluginsDistDir, distRoot.file("xide.sh"), distRoot.file("xide.bat"))
}

val syncDistLayout by tasks.registering(Copy::class) {
    description = "Assembles dist layout compatible with the existing launcher architecture"
    group = "distribution"

    dependsOn(cleanDistRuntime, tasks.named("jar"), configurations.runtimeClasspath, prepareBundledTemurinJdks, writeDistLauncher)
    into(distRoot)

    val appJar = tasks.named<Jar>("jar").flatMap { it.archiveFile }

    from(appJar) {
        into("app")
        rename { "xide.jar" }
    }

    from(configurations.runtimeClasspath) {
        into("lib")
        exclude("xide-*-plugin-*.jar")
    }

    from(configurations.runtimeClasspath) {
        into("plugins")
        include("xide-*-plugin-*.jar")
    }

    from(generatedLauncherSh) {
        into("")
        rename { "xide.sh" }
        filePermissions {
            user {
                read = true
                write = true
                execute = true
            }
            group {
                read = true
                execute = true
            }
            other {
                read = true
                execute = true
            }
        }
    }

    from(generatedLauncherBat) {
        into("")
        rename { "xide.bat" }
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named("assemble") {
    dependsOn(syncDistLayout)
}
