/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":xide-core"))
    api(libs.com.formdev.flatlaf)
    api(libs.com.formdev.flatlaf.extras)
    api(libs.com.formdev.flatlaf.intellij.themes)
    api(libs.com.fifesoft.rsyntaxtextarea)
    api(libs.com.fifesoft.autocomplete)
    api(libs.org.jetbrains.pty4j.pty4j)
    api(libs.org.jetbrains.jediterm.jediterm.ui)
    api(libs.org.jetbrains.jediterm.jediterm.core)
    testImplementation(libs.junit.junit)
    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
    testCompileOnly(libs.org.projectlombok.lombok)
    testAnnotationProcessor(libs.org.projectlombok.lombok)
}

description = "xide-ui"
